[linux-rt-lts]
source = "git"
git = "https://gitlab.archlinux.org/archlinux/packaging/upstream/linux-rt-lts"
include_regex = '^v[\d.]+-rt([\d]+)-(arch[\d]+)$'
from_pattern = 'v([\d.]+)-(rt[\d]+)-(arch[\d]+)'
to_pattern = '\1.\2.\3'
