version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "guid.patch",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-Fix-HTTP-query-in-web-interface-fixes-954.patch",
    "cups-2.4.0-statedir.patch",
    "cups-freebind.patch",
]
SPDX-FileCopyrightText = "cups contributors"
SPDX-License-Identifier = "Apache-2.0"
