version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "eigen-vectorized-reduction-half.patch",
]
SPDX-FileCopyrightText = "Copyright (C) 2008 Gael Guennebaud <gael.guennebaud@inria.fr>, Copyright (C) 2007-2011 Benoit Jacob <jacob.benoit.1@gmail.com>"
SPDX-License-Identifier = "MPL-2.0"
