[python-scrypt]
source = "git"
git = "https://github.com/holgern/py-scrypt.git"
prefix = "v"
# Ignore old invalid tag https://github.com/holgern/py-scrypt/releases/tag/1.0.59
exclude_regex = "1.0.59"
