version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "tmpfiles.conf",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "add-generated-protobuf-files.patch",
    "add-translations.patch",
    "fix-setup.py.patch",
    "fix-systemd-service.patch",
    "remove-debian-path.patch",
    "template-version-strings.patch",
    "use-system-python-packages.patch",
]
SPDX-FileCopyrightText = "opensnitch contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
