version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "add-algorithm-include-gcc-14.patch",
]
SPDX-FileCopyrightText = "openrct2 contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "googletest-fix-maybe-uninitialized.patch",
]
SPDX-FileCopyrightText = "googletest contributors"
SPDX-License-Identifier = "BSD-3-Clause"
