[xfce4-sensors-plugin]
source = "git"
git = "https://gitlab.xfce.org/panel-plugins/xfce4-sensors-plugin.git"
prefix = "xfce4-sensors-plugin-"
exclude_regex = ".*BMEURER_.*|1.*|Release.*|release_.*|help.*"
