pre_remove() {
	sed -i '/cryptsetup/d' /etc/s6/sv/mount-filesystems/dependencies
}

post_install() {
	if ! grep -q cryptsetup /etc/s6/sv/mount-filesystems/dependencies; then
		echo "cryptsetup" >> /etc/s6/sv/mount-filesystems/dependencies
	fi
	echo "  cryptsetup-s6 automatically installs itself into the boot bundle."
	echo "  There's no need to add it to the default bundle."
}

post_upgrade() {
	post_install
}

