version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "Xsession",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "lxdm-default-config.patch",
    "lxdm-fallback-interface.patch",
    "lxdm-git-fixes.patch",
    "lxdm-set-path.patch",
]
SPDX-FileCopyrightText = "lxdm contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
