version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "gcc-ada-repro.patch",
]
SPDX-FileCopyrightText = "ArchLinux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "c89",
]
SPDX-FileCopyrightText = "ArchLinux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "c99",
]
SPDX-FileCopyrightText = "ArchLinux contributors"
SPDX-License-Identifier = "0BSD"
