version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "dvd+rw-tools-7.0-dvddl.patch",
    "dvd+rw-tools-7.0-glibc2.6.90.patch",
    "dvd+rw-tools-7.0-reload.patch",
    "dvd+rw-tools-7.0-wctomb.patch",
    "dvd+rw-tools-7.0-wexit.patch",
    "dvd+rw-tools-7.1-bluray_pow_freespace.patch",
    "dvd+rw-tools-7.1-bluray_srm+pow.patch",
    "dvd+rw-tools-7.1-format.patch",
    "dvd+rw-tools-7.1-lastshort.patch",
    "dvd+rw-tools-7.1-layerbreaksetup.patch",
    "dvd+rw-tools-7.1-noevent.patch",
    "dvd+rw-tools-7.1-sysmacro-inc.patch",
]
SPDX-FileCopyrightText = "dvd+rw-tools contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
