[rpm-tools]
source = "git"
git = "https://github.com/rpm-software-management/rpm.git"
include_regex = '^rpm-([\d.]+)-release$'
from_pattern = '^rpm-([\d.]+)-release$'
to_pattern = '\1'
use_max_tag = true
