[ttf-roboto-mono]
source = "cmd"
cmd = "curl -s --location --header \"Accept: application/rdf+xml\" https://raw.githubusercontent.com/googlefonts/RobotoMono/main/sources/RobotoMono-Regular.ufo/fontinfo.plist | xmllint --xpath \"concat(//plist/dict/key[.='versionMajor']/following-sibling::integer, '.', substring(string(1000 + //plist/dict/key[.='versionMinor']/following-sibling::integer), 2))\" -"
