post_install() {
    _pkgname=regreet
    echo "Sample configuration file installed at /usr/share/doc/$_pkgname/$_pkgname.sample.toml"
}

post_upgrade() {
 if [ "`vercmp $2 0.1.1-3`" -lt 0 ]; then
   cat << _EOF
  ==> greetd-regreet oldpkgver < 0.1.1-3 detected!
  ==> 
  ==> This version allows to replace "cage" compositor with any 
  ==> any other supported "wayland-compositor", e.g. "sway".
  ==> 
  ==> remember to adopt your changes to /etc/greetd/regreet.toml
_EOF
 fi
}

