version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "1.12.4-shared_nowide.patch",
    "boost-1.89.patch",
    "librapidjson-1.1.patch",
]
SPDX-FileCopyrightText = "leatherman contributors"
SPDX-License-Identifier = "Apache-2.0"
