[thunderbird]
source = "jq"
url = "https://product-details.mozilla.org/1.0/thunderbird_versions.json"
filter = ".LATEST_THUNDERBIRD_VERSION"
from_pattern = '(\d+)\.(\d+)\.(\d+)esr'
to_pattern = '\1.\2.\3'
