[postgresql-old-upgrade]
source = "htmlparser"
url = "https://www.postgresql.org/support/versioning/"
xpath = '//h2[text()="Releases"]/following-sibling::table[1]/tbody/tr[2]/td[2]/text()'
include_regex = '\d+\.\d+'
