version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "grub.default",
    "keys/**",
    "sbat.csv",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-00_header-add-GRUB_COLOR_-variables.patch",
    "0002-10_linux-detect-archlinux-initramfs.patch",
    "0003-support-dropins-for-default-configuration.patch",
    "0004-po-Update-Translations-to-Build-with-Gettext-0.26.patch",
]
SPDX-FileCopyrightText = "grub contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
