version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "android-tools-35.0.2-fix-protobuf-30.0-compilation.patch",
    "fix-fastboot-flash.patch",
]
SPDX-FileCopyrightText = "android-tools contributors"
SPDX-License-Identifier = "Apache-2.0"
