version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "my.cnf",
    "mysql-user.conf",
    "mysqlrouter-user.conf",

]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "gcc-14.patch",
    "mysql-build-fix.patch",
    "openldap-2.5.patch",
    "protobuf-23.patch",
]
SPDX-FileCopyrightText = "percona-server contributors"
SPDX-License-Identifier = "0BSD"
