version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "python3.12-imp.patch",
    "python3.12-six.patch",
    "qt5-webengine-ffmpeg5.patch",
    "qt5-webengine-ffmpeg7.patch",
    "qt5-webengine-gcc-15.patch",
    "qt5-webengine-icu-75.patch",
    "qt5-webengine-ninja-1.12.patch",
    "qt5-webengine-pipewire-0.3.patch",
]
SPDX-FileCopyrightText = "qt5-webengine contributors"
SPDX-License-Identifier = "BSD-3-Clause"
