version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    ".gitignore",
    "nvidia-drm-outputclass.conf",
    "nvidia-sleep.conf",
    "nvidia.rules",
    "systemd-homed-override.conf",
    "systemd-suspend-override.conf",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-Enable-atomic-kernel-modesetting-by-default.patch",
    "0002-Add-IBT-support.patch",
]
SPDX-FileCopyrightText = "nvidia-utils contributors"
SPDX-License-Identifier = "MIT AND GPL-2.0-only"
