version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "no-thanks-poetry.patch",
]
SPDX-FileCopyrightText = "python-josepy contributors"
SPDX-License-Identifier = "Apache-2.0"
