[steam]
source = "apt"
mirror = "https://repo.steampowered.com/steam"
srcpkg = "steam"
suite = "stable"
repo = "steam"
strip_release = "true"
# ignore the APT epoch
from_pattern = "\\d+:(.+)"
to_pattern = "\\1"
