post_install() {
  cat <<MSG

  There are two alternative - preformance optimized - ungoogled-chromium packages available
  in the 'artist' repo https://wiki.artixlinux.org/Main/Repositories#artist_repository :

  - ungoogled-chromiun-avx2  : optimized with AVX2, x86_64-v3, PGO and more
  - ungoogled-chromiun-sse41 : optimized with SSE41, PGO and more (for older machines)

MSG
}

post_upgrade() {
  post_install
}

