[inkscape]
source = "git"
git = "https://gitlab.com/inkscape/inkscape.git"
use_latest_tag = true
sort_version_key = "vercmp"
from_pattern = 'INKSCAPE_(\d+)_(\d+)_(\d+)'
to_pattern = '\1.\2.\3'
exclude_regex = ".*(RC|BETA).*"
