version = 1

[[annotations]]
path = [
    "*.desktop",
    "*.hook",
    "*.install",
    "*.logrotate",
    "*.pam",
    "*.pc",
    "*.service",
    "*.socket",
    "*.sysusers",
    "*.timer",
    "*.tmpfiles",
    ".SRCINFO",
    ".nvchecker.toml",
    "PKGBUILD",
    "README.md",
    "keys/**",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = "*.patch"
SPDX-FileCopyrightText = "TinyXML contributors"
SPDX-License-Identifier = "Zlib"
