version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-proc_ops-struct.patch",
    "0002-kernel-5.7.patch",
    "0003-kernel-5.18.patch",
]
SPDX-FileCopyrightText = "bbswitch contributors"
SPDX-License-Identifier = "GPL-2.0-only"
