# Maintainer: Christian Hesse <mail@eworm.de>
# Contributor: Eric Bélanger <eric@archlinux.org>

pkgname=putty
pkgver=0.84
pkgrel=2
pkgdesc='A terminal integrated SSH/Telnet client'
arch=('x86_64')
url='https://putty.software/'
license=('MIT')
depends=(
  'glibc'
  'gtk3' 'libgdk-3.so' 'libgtk-3.so'
  'glib2' 'libglib-2.0.so' 'libgobject-2.0.so'
  'cairo' 'libcairo.so' 'libpangocairo-1.0.so' 'libpango-1.0.so'
  'gdk-pixbuf2' 'libgdk_pixbuf-2.0.so'
  'pango' 'libpangocairo-1.0.so' 'libpango-1.0.so')
makedepends=('cmake' 'git' 'halibut')
validpgpkeys=('F412BA3AA30FDC0E77B4E3871993D21BCAD1AA77') # PuTTY Releases <putty@projects.tartarus.org>
source=("git+https://git.tartarus.org/simon/putty.git#tag=${pkgver}"
        'putty.desktop'
        'putty.png'
        'putty.xpm')
sha256sums=('9cd9a84497535baa5df5a675c367bfe2bdbf0cbcec54f24993e2110bf66f94ab'
            '4a8af81fe8ac702ad298606076088f237b83beed82cc089a32f314888b67cf2c'
            '93ba8ea8abf942f4de1c6cd167d4b5c2d6246fb1aa39dc49571cc18d167460c1'
            'd65139883171ed0119d9778ff4a89e6a8151a5ae97fcf8dc7cafb59df424377f')

prepare() {
  # building from git, so inject proper version information
  cat >"${pkgname}"/version.h <<-EOF
	/* Generated by PKGBUILD */
	#define RELEASE ${pkgver}
	#define TEXTVER "Artix Linux package ${pkgver}-${pkgrel}"
	#define SSHVER "-Release-${pkgver}"
	#define BINARY_VERSION ${pkgver%.*},${pkgver#*.},0,${pkgrel}
	EOF
}

build() {
  # By default this builds with support for both, GTK+ and X11.
  # Just the first is fine, so disable X11 (and fix wayland).
  export CFLAGS+=' -DNOT_X_WINDOWS'

  cmake \
    -B build \
    -S "${pkgname}" \
    -DCMAKE_BUILD_TYPE='None' \
    -DCMAKE_INSTALL_PREFIX='/usr' \
    -Wno-dev
  cmake \
    --build build
}

package() {
  DESTDIR="${pkgdir}" cmake --install build
  
  install -D -m0644 "${srcdir}/${pkgname}"/LICENCE "${pkgdir}"/usr/share/licenses/"${pkgname}"/LICENSE
  install -D -m0644 "${srcdir}"/putty.desktop "${pkgdir}"/usr/share/applications/putty.desktop
  install -D -m0644 "${srcdir}"/putty.png "${pkgdir}"/usr/share/pixmaps/putty.png
  install -D -m0644 "${srcdir}"/putty.xpm "${pkgdir}"/usr/share/pixmaps/putty.xpm
}
