version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "keys/**",
    "*.sysusers",
    "*.tmpfiles"
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "remove-vendoring.patch",
]
SPDX-FileCopyrightText = "rpi-imager contributors"
SPDX-License-Identifier = "Apache-2.0"
