version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix-perl-errors.patch",
    "valgrind_3_22_0_fchmodat2_syscall.patch",
    "valgrind_3_22_0_s390x-linux_memfd_secret.patch",
    "valgrind-3.7.0-respect-flags.patch",
]
SPDX-FileCopyrightText = "valgrind contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
