version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "c12e8515.patch",
    "julia-curl-1.10.patch",
    "julia-hardcoded-libs.patch",
    "julia-libgit2-1.8.patch",
    "julia-libgit2-1.9.patch",
    "julia-metainfo.patch",
]
SPDX-FileCopyrightText = "julia contributors"
SPDX-License-Identifier = "MIT"
