[libreoffice-still]
source = "regex"
regex = 'LibreOffice \d+\.\d+\.\d+ \(\d{4}-\d{2}-\d{2}\) - Previous Release'
url = "https://www.libreoffice.org/download/release-notes/"
prefix = "LibreOffice "
from_pattern = '(\d+\.\d+\.\d+) \(.*?\) - Previous Release'
to_pattern = '\1'
