#!/bin/sh

export PATH="/usr/sbin:/usr/bin:/sbin:/bin"

. /etc/artix/cgroups.conf
if [ "${CG_CHILD}" = "true" ]; then
	CG_PARAM="-b /sys/fs/cgroup/${CG_CHILD_NAME}"
fi

exec /usr/bin/dinit ${CG_PARAM} "$@"
