version = 1

[[annotations]]
path = [
  "PKGBUILD",
  "README.md",
  "keys/**",
  ".SRCINFO",
  ".nvchecker.toml",
  "*.install",
  "*.sysusers",
  "*.tmpfiles",
  "*.logrotate",
  "*.pam",
  "*.service",
  "*.socket",
  "*.timer",
  "*.desktop",
  "*.hook",
  "*.conf",
  "*.sh",
  "arch-release",
  "*.svg",
  "*.png",
  "crypttab",
  "fstab",
  "env-generator",
  "group",
  "gshadow",
  "hosts",
  "issue",
  "os-release",
  "passwd",
  "profile",
  "securetty",
  "shadow",
  "shells",
  "sysctl",
  "sysusers",
  "tmpfiles",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
