post_install() {
	echo "==> HINT: To register the runner on Gitea, run 'gitea-runner --config /etc/gitea-runner/config.yaml register' from '/var/lib/gitea-runner'"
	echo
	echo "==> HINT: To setup the runner with Docker, either:"
	echo "    - Add the 'gitea-runner' user to the 'docker' group (but be aware of the potential security implications: https://docs.docker.com/engine/security/#docker-daemon-attack-surface)"
	echo "    - Follow upstream documentation to setup the runner with rootless Docker: https://gitea.com/gitea/runner/src/branch/main/examples/vm/rootless-docker.md"
}
