version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "allow-using-system-gradle.patch",
    "skip-checks-for-git-repo.patch",
    "skip-failing-test.patch",
    "support-reproducible-builds.patch",
]
SPDX-FileCopyrightText = "solr contributors"
SPDX-License-Identifier = "TODO-Choose-a-license"
