version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "graphviz-13.patch",
]
SPDX-FileCopyrightText = "libmediainfo contributors"
SPDX-License-Identifier = "BSD-2-Clause"
