version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "gnome-panel-60.patch",
    "gnome-panel-75.patch",
    "gnome-panel-78.patch",
    "gnome-panel-79.patch",
    "gnome-panel-80.patch",
]
SPDX-FileCopyrightText = "gnome-panel contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
