[perl-time-modules]
source = "regex"
regex = 'Time-modules-\d+\.\d+\.tar.gz'
url = "https://cpan.metacpan.org/authors/id/M/MU/MUIR/modules/"
prefix = "Time-modules-"
from_pattern = ".tar.gz"
to_pattern = ""
