version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "*.uwsgi",
    "hyperkitty-1.3.5-settings.patch",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix_compatibility_with_mistune_3.1.x.patch",
]
SPDX-FileCopyrightText = "hyperkitty contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
