version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "adjust-tests-for-python3.patch",
]
SPDX-FileCopyrightText = "python-xmlschema contributors"
SPDX-License-Identifier = "MIT"
