[mesa]
source = "git"
git = "https://gitlab.freedesktop.org/mesa/mesa.git"
include_regex = 'mesa-\d+\.\d+\.[1-9]\d*'
#include_regex = 'mesa-.*'  # Unstable
prefix = "mesa-"
from_pattern = '-([a-z])'
to_pattern = '\1'
