[gnome-terminal]
source = "git"
git = "https://gitlab.gnome.org/GNOME/gnome-terminal.git"
include_regex = '\d+\.\d*[02468]\.\d+'
# include_regex = '\d+\.[012345678]\d?\.\d+' # Unstable, but not 3.90 series yet
